### ISSUE TITLE
feature: i18n for Japanese

### ISSUE THREAD

**Issue by satomikenta-org** [youzan/zent#1745] opened 2021-07-19 08:00 UTC
## Internationalization for Japanese.
---

`**i18n**`

**What is the current behavior?**
Only Chinese and English

**What is the expected behavior?**
Please Add Japanese

** link to ja.js and time-locale.js **
`https://github.com/satomikenta-org/zent-ui-ja/tree/master`

**Comment by cpylua** [comment] 2021-07-19 08:11
Hi,

Thanks for the Japanese translation!

Could you please convert https://github.com/satomikenta-org/zent-ui-ja/tree/master into a github Pull Request?

Github links for creating a PR:
- [Fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
- [Creating a pull request from a fork](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by satomikenta-org** [comment] 2021-07-19 09:30
Hi, 

I fork and commit (feature) .
Which base branch should I make 'pull request' to ?

**Comment by cpylua** [comment] 2021-07-19 10:10
> Hi, 
> 
> I forked and committed .
> Which base branch should I make 'pull request' to ?
> 
> and I don't understand how to test my code...
> sorry for that.

Create a pull request to `master` branch.

**Comment by cpylua** [comment] 2021-07-20 11:11
Duplicate of #1746.

**Closed by cpylua** 2021-07-20 11:11 UTC
